version: '3'

tasks:
  setup: {silent:true}
  default:
    silent: true
    cmds:
    - |- 
      if test -z "{{.P}}"
      then echo "plese specify prefix with P="
      else
        NOW=$(date +%s)
        TAG="{{.P}}-$NOW"
        git commit -m $TAG -a || true
        git tag $TAG
        git push origin main --tags
      fi
