# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: '3'
env:
  NOW:
    sh: date +%Y-%m%d-%H%M

tasks:
  default: task -l
  setup: {silent:true}

  1:
   desc: tag for kind
   cmds:
   - git tag kind-$NOW

  2:
    desc: tag for microk8s
    cmds:
    - git tag mk8s-$NOW

  3:
    desc: tag for k3ss
    cmds:
    - git tag k3s-$NOW

  go:
    desc: push tags to trigger build
    cmds:
    - git commit -m $NOW -a || true
    - git push origin main --tags

  enter: ssh -o "StrictHostKeyChecking=no" "ubuntu@$(cat ip.txt)"
  
  watch: watch kubectl -n nuvolaris get po,sts
