version: '3'
env:
  NOW:
    sh: date +%Y-%m%d-%H%M

tasks:
  default: task -l
  setup: {silent:true}

  1:
   desc: tag for kind
   cmds:
   - git tag kind-$NOW

  2:
    desc: tag for microk8s
    cmds:
    - git tag m8s-$NOW


  go:
    desc: push tags to trigger build
    cmds:
    - git commit -m $NOW -a || true
    - git push origin main --tags
  
