# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

version: '3'
env:
  NOW:
    sh: date +%Y-%m%d-%H%M

tasks:
  default: task -l
  setup: {silent:true}

  1:
    desc: tag for kind
    cmds:
    - git tag kind-$NOW
    - git push origin main --tags

  2:
    desc: tag for microk8s
    cmds:
    - git tag mk8s-$NOW
    - git push origin main --tags

  3:
    desc: tag for k3ss
    cmds:
    - git tag k3s-$NOW
    - git push origin main --tags

  debug:
    desc: debug
    cmds:
      - touch debug
      - git add debug
      - git commit -m $NOW -a || true

  snap:
    desc: commit
    cmds:
    - if test -e debug ; then git rm debug ; fi
    - git commit -m $NOW -a || true

  enter: ssh -o "StrictHostKeyChecking=no" "ubuntu@$(cat ip.txt)"
  
  watch: watch kubectl -n nuvolaris get po,sts

  progress: 
    - |
      if test -z "{{.N}}"
      then echo use task progress N=value
      else curl -L "https://geps.dev/progress/{{.N}}?dangerColor=006600&warningColor=006600&successColor=006600" >img/progress.svg
      fi
